### ISSUE TITLE
Overall code coherence

### ISSUE THREAD

**Issue by yklcs** [hyeokju1313/SangHyunChatbot#1]
https://github.com/hyeokju1313/SangHyunChatbot/blob/master/myproject/myproject/settings.py  points to a blank file, and other parts of code are missing

You committed /myproject/ and committed another directory under it with the same name

In /myproject/sanghyunfood/views.py, Line 20,
`((request.body).decode('utf-8'))`
You were trying to access the decode method and unneeded parentheses are added, should be 
`request.body.decode('utf-8')`
instead.

In /myproject/sanghyunfood/views.py, Line 32,
`meal = meals[0].text.replace('\n                           ', '')`
Is an extremely primitive way of replacing text. Consider using regex instead.

In /myproject/sanghyunfood/views.py, Line 36, format it correctly like 
`'text': "{}의{}입니다.\r\n{} ".format(today_date,return_str,meal)`

And you're not using version control/git properly. Initially commit all your changes at once, then commit your changes.

**Comment by hyeokju1313** [comment]
**Source updated**
